#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <buy>;
!slot <num>;
!slot <price>;
!slot <from>;
!slot <to>;
!slot <startStation>;
!slot <endStation>;
!slot <ticket>;

!start <buyTicket>;
<buyTicket>:<one>|<two>|<three>|<four>|<five>|<six>|<seven>;
<one>:<num>;
<two>:<price>;
<three>:<endStation>[站];
<four>:<buy><num><ticket>;
<five>:[<buy>][<num>]<price>[钱][<ticket>];
<six>:[<buy>][<num>][<to>]<endStation>[站][<ticket>];
<seven>:[<buy>][<num>][<from>][<startStation>][站][<to>]<endStation>[站][<ticket>];


<buy>:我想要买|我要买|我想买|帮我买|我买|买|我想要|我要|要|给我来|给我买|给我|来|购买;
<num>:张!id(10001)|一张!id(10001)|二张!id(10002)|两张!id(10002)|三张!id(10003)|四张!id(10004)|五张!id(10005)|六张!id(10006)|七张!id(10007)|八张!id(10008)|九张!id(10009)|十张!id(10010)|十一张!id(10011)|十二张!id(10012);
<price>:一元!id(20001)|二元!id(20002)|两元!id(20002)|三元!id(20003)|四元!id(20004)|五元!id(20005)|六元!id(20006)|七元!id(20007)|八元!id(20008)|九元!id(20009)|十元!id(20010)|十一元!id(20011)|十二元!id(20012)|一块!id(20001)|二块!id(20002)|两块!id(20002)|三块!id(20003)|四块!id(20004)|五块!id(20005)|六块!id(20006)|七块!id(20007)|八块!id(20008)|九块!id(20009)|十块!id(20010)|十一块!id(20011)|十二块!id(20012);
<from>:从;
<to>:去|到;
<startStation>:红山!id(30001)|谷水!id(30002)|秦岭路!id(30003)|武汉路!id(30004)|长安路!id(30005)|上海市场!id(30006)|牡丹广场!id(30007)|七里河!id(30008)|王城公园!id(30009)|解放路!id(30010)|周王城广场!id(30011)|丽景门!id(30012)|应天门!id(30013)|青年宫!id(30014)|夹马营!id(30015)|启明南路!id(30016)|塔湾!id(30017)|史家湾!id(30018)|杨湾!id(30019);
<endStation>:红山!id(30001)|谷水!id(30002)|秦岭路!id(30003)|武汉路!id(30004)|长安路!id(30005)|上海市场!id(30006)|牡丹广场!id(30007)|七里河!id(30008)|王城公园!id(30009)|解放路!id(30010)|周王城广场!id(30011)|丽景门!id(30012)|应天门!id(30013)|青年宫!id(30014)|夹马营!id(30015)|启明南路!id(30016)|塔湾!id(30017)|史家湾!id(30018)|杨湾!id(30019);
<ticket>:的票|的车票|的单程票|的单程票|的地铁票|票|车票|地铁票;